// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trhazvxbpwecywvxkkqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyaGF6dnhicHdlY3l3dnhra3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjY5OTQsImV4cCI6MjA2MDU0Mjk5NH0.o5XzTv-2zTKRe-GOcUcfTH-GkO7o_b1SFSF7QW943bA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);